name: Install CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  dependencies-integrity:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - run: npm install
      - name: Check no changes
        run: git diff --quiet ./package-lock.json || exit 1
